/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/Inline_response_200.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



Inline_response_200::Inline_response_200()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Recipients = 0;
    m_RecipientsIsSet = false;
    m_External_id = utility::conversions::to_string_t("");
    m_External_idIsSet = false;
    m_ErrorsIsSet = false;
}

Inline_response_200::~Inline_response_200()
{
}

void Inline_response_200::validate()
{
    // TODO: implement validation
}

web::json::value Inline_response_200::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_RecipientsIsSet)
    {
        val[utility::conversions::to_string_t(U("recipients"))] = ModelBase::toJson(m_Recipients);
    }
    if(m_External_idIsSet)
    {
        val[utility::conversions::to_string_t(U("external_id"))] = ModelBase::toJson(m_External_id);
    }
    if(m_ErrorsIsSet)
    {
        val[utility::conversions::to_string_t(U("errors"))] = ModelBase::toJson(m_Errors);
    }

    return val;
}

bool Inline_response_200::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_id;
            ok &= ModelBase::fromJson(fieldValue, refVal_id);
            setId(refVal_id);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("recipients"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("recipients")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_recipients;
            ok &= ModelBase::fromJson(fieldValue, refVal_recipients);
            setRecipients(refVal_recipients);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("external_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("external_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_external_id;
            ok &= ModelBase::fromJson(fieldValue, refVal_external_id);
            setExternalId(refVal_external_id);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("errors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("errors")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Notification200Errors> refVal_errors;
            ok &= ModelBase::fromJson(fieldValue, refVal_errors);
            setErrors(refVal_errors);
        }
    }
    return ok;
}

void Inline_response_200::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_RecipientsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("recipients")), m_Recipients));
    }
    if(m_External_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("external_id")), m_External_id));
    }
    if(m_ErrorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("errors")), m_Errors));
    }
}

bool Inline_response_200::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_id;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_id );
        setId(refVal_id);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("recipients"))))
    {
        int32_t refVal_recipients;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("recipients"))), refVal_recipients );
        setRecipients(refVal_recipients);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("external_id"))))
    {
        utility::string_t refVal_external_id;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("external_id"))), refVal_external_id );
        setExternalId(refVal_external_id);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("errors"))))
    {
        std::shared_ptr<Notification200Errors> refVal_errors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("errors"))), refVal_errors );
        setErrors(refVal_errors);
    }
    return ok;
}

utility::string_t Inline_response_200::getId() const
{
    return m_Id;
}

void Inline_response_200::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Inline_response_200::idIsSet() const
{
    return m_IdIsSet;
}

void Inline_response_200::unsetId()
{
    m_IdIsSet = false;
}
int32_t Inline_response_200::getRecipients() const
{
    return m_Recipients;
}

void Inline_response_200::setRecipients(int32_t value)
{
    m_Recipients = value;
    m_RecipientsIsSet = true;
}

bool Inline_response_200::recipientsIsSet() const
{
    return m_RecipientsIsSet;
}

void Inline_response_200::unsetRecipients()
{
    m_RecipientsIsSet = false;
}
utility::string_t Inline_response_200::getExternalId() const
{
    return m_External_id;
}

void Inline_response_200::setExternalId(const utility::string_t& value)
{
    m_External_id = value;
    m_External_idIsSet = true;
}

bool Inline_response_200::externalIdIsSet() const
{
    return m_External_idIsSet;
}

void Inline_response_200::unsetExternal_id()
{
    m_External_idIsSet = false;
}
std::shared_ptr<Notification200Errors> Inline_response_200::getErrors() const
{
    return m_Errors;
}

void Inline_response_200::setErrors(const std::shared_ptr<Notification200Errors>& value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}

bool Inline_response_200::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void Inline_response_200::unsetErrors()
{
    m_ErrorsIsSet = false;
}
}
}
}
}


