/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/Inline_response_200_3.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



Inline_response_200_3::Inline_response_200_3()
{
    m_In_app_messagesIsSet = false;
}

Inline_response_200_3::~Inline_response_200_3()
{
}

void Inline_response_200_3::validate()
{
    // TODO: implement validation
}

web::json::value Inline_response_200_3::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_In_app_messagesIsSet)
    {
        val[utility::conversions::to_string_t(U("in_app_messages"))] = ModelBase::toJson(m_In_app_messages);
    }

    return val;
}

bool Inline_response_200_3::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("in_app_messages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("in_app_messages")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Object>> refVal_setInAppMessages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInAppMessages);
            setInAppMessages(refVal_setInAppMessages);
        }
    }
    return ok;
}

void Inline_response_200_3::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_In_app_messagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("in_app_messages")), m_In_app_messages));
    }
}

bool Inline_response_200_3::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("in_app_messages"))))
    {
        std::vector<std::shared_ptr<Object>> refVal_setInAppMessages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("in_app_messages"))), refVal_setInAppMessages );
        setInAppMessages(refVal_setInAppMessages);
    }
    return ok;
}

std::vector<std::shared_ptr<Object>>& Inline_response_200_3::getInAppMessages()
{
    return m_In_app_messages;
}

void Inline_response_200_3::setInAppMessages(const std::vector<std::shared_ptr<Object>>& value)
{
    m_In_app_messages = value;
    m_In_app_messagesIsSet = true;
}

bool Inline_response_200_3::inAppMessagesIsSet() const
{
    return m_In_app_messagesIsSet;
}

void Inline_response_200_3::unsetIn_app_messages()
{
    m_In_app_messagesIsSet = false;
}
}
}
}
}


