/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/Inline_response_400_3.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



Inline_response_400_3::Inline_response_400_3()
{
    m_ErorrsIsSet = false;
}

Inline_response_400_3::~Inline_response_400_3()
{
}

void Inline_response_400_3::validate()
{
    // TODO: implement validation
}

web::json::value Inline_response_400_3::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ErorrsIsSet)
    {
        val[utility::conversions::to_string_t(U("erorrs"))] = ModelBase::toJson(m_Erorrs);
    }

    return val;
}

bool Inline_response_400_3::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("erorrs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("erorrs")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_erorrs;
            ok &= ModelBase::fromJson(fieldValue, refVal_erorrs);
            setErorrs(refVal_erorrs);
        }
    }
    return ok;
}

void Inline_response_400_3::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ErorrsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("erorrs")), m_Erorrs));
    }
}

bool Inline_response_400_3::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("erorrs"))))
    {
        std::vector<utility::string_t> refVal_erorrs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("erorrs"))), refVal_erorrs );
        setErorrs(refVal_erorrs);
    }
    return ok;
}

std::vector<utility::string_t>& Inline_response_400_3::getErorrs()
{
    return m_Erorrs;
}

void Inline_response_400_3::setErorrs(const std::vector<utility::string_t>& value)
{
    m_Erorrs = value;
    m_ErorrsIsSet = true;
}

bool Inline_response_400_3::erorrsIsSet() const
{
    return m_ErorrsIsSet;
}

void Inline_response_400_3::unsetErorrs()
{
    m_ErorrsIsSet = false;
}
}
}
}
}


