/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/NotificationSlice.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



NotificationSlice::NotificationSlice()
{
    m_Total_count = 0;
    m_Total_countIsSet = false;
    m_Offset = 0;
    m_OffsetIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_NotificationsIsSet = false;
}

NotificationSlice::~NotificationSlice()
{
}

void NotificationSlice::validate()
{
    // TODO: implement validation
}

web::json::value NotificationSlice::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Total_countIsSet)
    {
        val[utility::conversions::to_string_t(U("total_count"))] = ModelBase::toJson(m_Total_count);
    }
    if(m_OffsetIsSet)
    {
        val[utility::conversions::to_string_t(U("offset"))] = ModelBase::toJson(m_Offset);
    }
    if(m_LimitIsSet)
    {
        val[utility::conversions::to_string_t(U("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_NotificationsIsSet)
    {
        val[utility::conversions::to_string_t(U("notifications"))] = ModelBase::toJson(m_Notifications);
    }

    return val;
}

bool NotificationSlice::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("total_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalCount);
            setTotalCount(refVal_setTotalCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("offset"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("offset")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOffset;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOffset);
            setOffset(refVal_setOffset);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("notifications"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("notifications")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<NotificationWithMeta>> refVal_setNotifications;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotifications);
            setNotifications(refVal_setNotifications);
        }
    }
    return ok;
}

void NotificationSlice::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Total_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total_count")), m_Total_count));
    }
    if(m_OffsetIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("offset")), m_Offset));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("limit")), m_Limit));
    }
    if(m_NotificationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("notifications")), m_Notifications));
    }
}

bool NotificationSlice::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("total_count"))))
    {
        int32_t refVal_setTotalCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total_count"))), refVal_setTotalCount );
        setTotalCount(refVal_setTotalCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("offset"))))
    {
        int32_t refVal_setOffset;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("offset"))), refVal_setOffset );
        setOffset(refVal_setOffset);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("notifications"))))
    {
        std::vector<std::shared_ptr<NotificationWithMeta>> refVal_setNotifications;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("notifications"))), refVal_setNotifications );
        setNotifications(refVal_setNotifications);
    }
    return ok;
}

int32_t NotificationSlice::getTotalCount() const
{
    return m_Total_count;
}

void NotificationSlice::setTotalCount(int32_t value)
{
    m_Total_count = value;
    m_Total_countIsSet = true;
}

bool NotificationSlice::totalCountIsSet() const
{
    return m_Total_countIsSet;
}

void NotificationSlice::unsetTotal_count()
{
    m_Total_countIsSet = false;
}
int32_t NotificationSlice::getOffset() const
{
    return m_Offset;
}

void NotificationSlice::setOffset(int32_t value)
{
    m_Offset = value;
    m_OffsetIsSet = true;
}

bool NotificationSlice::offsetIsSet() const
{
    return m_OffsetIsSet;
}

void NotificationSlice::unsetOffset()
{
    m_OffsetIsSet = false;
}
int32_t NotificationSlice::getLimit() const
{
    return m_Limit;
}

void NotificationSlice::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool NotificationSlice::limitIsSet() const
{
    return m_LimitIsSet;
}

void NotificationSlice::unsetLimit()
{
    m_LimitIsSet = false;
}
std::vector<std::shared_ptr<NotificationWithMeta>>& NotificationSlice::getNotifications()
{
    return m_Notifications;
}

void NotificationSlice::setNotifications(const std::vector<std::shared_ptr<NotificationWithMeta>>& value)
{
    m_Notifications = value;
    m_NotificationsIsSet = true;
}

bool NotificationSlice::notificationsIsSet() const
{
    return m_NotificationsIsSet;
}

void NotificationSlice::unsetNotifications()
{
    m_NotificationsIsSet = false;
}
}
}
}
}


