/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_notification_request_body.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_Get_notification_request_body_H_
#define COM_ONESIGNAL_CLIENT_MODEL_Get_notification_request_body_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Get_notification_request_body
    : public ModelBase
{
public:
    Get_notification_request_body();
    virtual ~Get_notification_request_body();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Get_notification_request_body members

    /// <summary>
    /// -&gt; \&quot;sent\&quot; - All the devices by player_id that were sent the specified notification_id.  Notifications targeting under 1000 recipients will not have \&quot;sent\&quot; events recorded, but will show \&quot;clicked\&quot; events. \&quot;clicked\&quot; - All the devices by &#x60;player_id&#x60; that clicked the specified notification_id.
    /// </summary>
    utility::string_t getEvents() const;
    bool eventsIsSet() const;
    void unsetEvents();

    void setEvents(const utility::string_t& value);

    /// <summary>
    /// The email address you would like the report sent.
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();

    void setEmail(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAppId() const;
    bool appIdIsSet() const;
    void unsetApp_id();

    void setAppId(const utility::string_t& value);


protected:
    utility::string_t m_Events;
    bool m_EventsIsSet;
    utility::string_t m_Email;
    bool m_EmailIsSet;
    utility::string_t m_App_id;
    bool m_App_idIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_Get_notification_request_body_H_ */
