/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_7.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_7_H_
#define COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_7_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Inline_response_200_7
    : public ModelBase
{
public:
    Inline_response_200_7();
    virtual ~Inline_response_200_7();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Inline_response_200_7 members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSuccess() const;
    bool successIsSet() const;
    void unsetSuccess();

    void setSuccess(const utility::string_t& value);


protected:
    utility::string_t m_Success;
    bool m_SuccessIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_7_H_ */
