/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_3.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_3_H_
#define COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_3_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/Object.h"
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Inline_response_200_3
    : public ModelBase
{
public:
    Inline_response_200_3();
    virtual ~Inline_response_200_3();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Inline_response_200_3 members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Object>>& getInAppMessages();
    bool inAppMessagesIsSet() const;
    void unsetIn_app_messages();

    void setInAppMessages(const std::vector<std::shared_ptr<Object>>& value);


protected:
    std::vector<std::shared_ptr<Object>> m_In_app_messages;
    bool m_In_app_messagesIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_Inline_response_200_3_H_ */
