/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PlayerSlice.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_PlayerSlice_H_
#define COM_ONESIGNAL_CLIENT_MODEL_PlayerSlice_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/Player.h"
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {

class Player;

/// <summary>
/// 
/// </summary>
class  PlayerSlice
    : public ModelBase
{
public:
    PlayerSlice();
    virtual ~PlayerSlice();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PlayerSlice members

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotalCount() const;
    bool totalCountIsSet() const;
    void unsetTotal_count();

    void setTotalCount(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getOffset() const;
    bool offsetIsSet() const;
    void unsetOffset();

    void setOffset(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();

    void setLimit(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Player>>& getPlayers();
    bool playersIsSet() const;
    void unsetPlayers();

    void setPlayers(const std::vector<std::shared_ptr<Player>>& value);


protected:
    int32_t m_Total_count;
    bool m_Total_countIsSet;
    int32_t m_Offset;
    bool m_OffsetIsSet;
    int32_t m_Limit;
    bool m_LimitIsSet;
    std::vector<std::shared_ptr<Player>> m_Players;
    bool m_PlayersIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_PlayerSlice_H_ */
