/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User_subscription_options.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_User_subscription_options_H_
#define COM_ONESIGNAL_CLIENT_MODEL_User_subscription_options_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"


namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  User_subscription_options
    : public ModelBase
{
public:
    User_subscription_options();
    virtual ~User_subscription_options();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// User_subscription_options members

    /// <summary>
    /// 
    /// </summary>
    bool isRetainPreviousOwner() const;
    bool retainPreviousOwnerIsSet() const;
    void unsetRetain_previous_owner();

    void setRetainPreviousOwner(bool value);


protected:
    bool m_Retain_previous_owner;
    bool m_Retain_previous_ownerIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_User_subscription_options_H_ */
